# version: '3.8'

# services:
#   postgres:
#     image: postgres:13
#     environment:

#       POSTGRES_USER: nuts_user
#       POSTGRES_PASSWORD: nuts_pass
#       POSTGRES_DB: nuts_db
#     ports:
#       - "5432:5432"
#     volumes:
#       - pgdata:/var/lib/postgresql/data

#   nats:
#     image: nats:latest
#     ports:
#       - "4222:4222"

# volumes:
#   pgdata:





services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: nuts_user
      POSTGRES_PASSWORD: nuts_pass
      POSTGRES_DB: nuts_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  nats:
    image: nats:latest
    ports:
      - "4222:4222"

  app:
    build: .
    environment:
      - NATS_URL=nats://18.234.166.68:4222  # ✅ Set remote NATS server URL here
      - POSTGRES_USER=nuts_user
      - POSTGRES_PASSWORD=nuts_pass
      - POSTGRES_DB=nuts_db
      - POSTGRES_HOST=postgres
    depends_on:
      - postgres
    command: python main.py  # or your actual entry point

volumes:
  pgdata:
